/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResortEditsRouteImport } from './routes/resort-edits'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PortofinoRouteImport } from './routes/portofino'
import { Route as MyEditRouteImport } from './routes/my-edit'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PortofinoDay5RouteImport } from './routes/portofino.day-5'
import { Route as PortofinoDay4RouteImport } from './routes/portofino.day-4'
import { Route as PortofinoDay3RouteImport } from './routes/portofino.day-3'
import { Route as PortofinoDay2RouteImport } from './routes/portofino.day-2'
import { Route as PortofinoDay1RouteImport } from './routes/portofino.day-1'
import { Route as PortofinoMomentRouteImport } from './routes/portofino.$moment'
import { Route as LookSlugRouteImport } from './routes/look.$slug'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as BrandsSlugRouteImport } from './routes/brands.$slug'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminProductVaultRouteImport } from './routes/admin.product-vault'
import { Route as AdminInventoryHealthRouteImport } from './routes/admin.inventory-health'
import { Route as AdminFounderLooksRouteImport } from './routes/admin.founder-looks'
import { Route as AdminEditorialMemoryRouteImport } from './routes/admin.editorial-memory'
import { Route as AdminDestinationMomentsRouteImport } from './routes/admin.destination-moments'
import { Route as AdminDayImagesRouteImport } from './routes/admin.day-images'
import { Route as AdminBuyingOfficeRouteImport } from './routes/admin.buying-office'
import { Route as AdminBrandsRouteImport } from './routes/admin.brands'
import { Route as PortofinoDayLookRouteImport } from './routes/portofino.$day.$look'
import { Route as AdminHeroOutfitIdRouteImport } from './routes/admin.hero-outfit.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResortEditsRoute = ResortEditsRouteImport.update({
  id: '/resort-edits',
  path: '/resort-edits',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortofinoRoute = PortofinoRouteImport.update({
  id: '/portofino',
  path: '/portofino',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEditRoute = MyEditRouteImport.update({
  id: '/my-edit',
  path: '/my-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortofinoDay5Route = PortofinoDay5RouteImport.update({
  id: '/day-5',
  path: '/day-5',
  getParentRoute: () => PortofinoRoute,
} as any)
const PortofinoDay4Route = PortofinoDay4RouteImport.update({
  id: '/day-4',
  path: '/day-4',
  getParentRoute: () => PortofinoRoute,
} as any)
const PortofinoDay3Route = PortofinoDay3RouteImport.update({
  id: '/day-3',
  path: '/day-3',
  getParentRoute: () => PortofinoRoute,
} as any)
const PortofinoDay2Route = PortofinoDay2RouteImport.update({
  id: '/day-2',
  path: '/day-2',
  getParentRoute: () => PortofinoRoute,
} as any)
const PortofinoDay1Route = PortofinoDay1RouteImport.update({
  id: '/day-1',
  path: '/day-1',
  getParentRoute: () => PortofinoRoute,
} as any)
const PortofinoMomentRoute = PortofinoMomentRouteImport.update({
  id: '/$moment',
  path: '/$moment',
  getParentRoute: () => PortofinoRoute,
} as any)
const LookSlugRoute = LookSlugRouteImport.update({
  id: '/look/$slug',
  path: '/look/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)
const BrandsSlugRoute = BrandsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BrandsRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/admin/subscribers',
  path: '/admin/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductVaultRoute = AdminProductVaultRouteImport.update({
  id: '/admin/product-vault',
  path: '/admin/product-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryHealthRoute = AdminInventoryHealthRouteImport.update({
  id: '/admin/inventory-health',
  path: '/admin/inventory-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFounderLooksRoute = AdminFounderLooksRouteImport.update({
  id: '/admin/founder-looks',
  path: '/admin/founder-looks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditorialMemoryRoute = AdminEditorialMemoryRouteImport.update({
  id: '/admin/editorial-memory',
  path: '/admin/editorial-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDestinationMomentsRoute = AdminDestinationMomentsRouteImport.update({
  id: '/admin/destination-moments',
  path: '/admin/destination-moments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDayImagesRoute = AdminDayImagesRouteImport.update({
  id: '/admin/day-images',
  path: '/admin/day-images',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuyingOfficeRoute = AdminBuyingOfficeRouteImport.update({
  id: '/admin/buying-office',
  path: '/admin/buying-office',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrandsRoute = AdminBrandsRouteImport.update({
  id: '/admin/brands',
  path: '/admin/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const PortofinoDayLookRoute = PortofinoDayLookRouteImport.update({
  id: '/$day/$look',
  path: '/$day/$look',
  getParentRoute: () => PortofinoRoute,
} as any)
const AdminHeroOutfitIdRoute = AdminHeroOutfitIdRouteImport.update({
  id: '/admin/hero-outfit/$id',
  path: '/admin/hero-outfit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRouteWithChildren
  '/destinations': typeof DestinationsRouteWithChildren
  '/my-edit': typeof MyEditRoute
  '/portofino': typeof PortofinoRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resort-edits': typeof ResortEditsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/buying-office': typeof AdminBuyingOfficeRoute
  '/admin/day-images': typeof AdminDayImagesRoute
  '/admin/destination-moments': typeof AdminDestinationMomentsRoute
  '/admin/editorial-memory': typeof AdminEditorialMemoryRoute
  '/admin/founder-looks': typeof AdminFounderLooksRoute
  '/admin/inventory-health': typeof AdminInventoryHealthRoute
  '/admin/product-vault': typeof AdminProductVaultRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/look/$slug': typeof LookSlugRoute
  '/portofino/$moment': typeof PortofinoMomentRoute
  '/portofino/day-1': typeof PortofinoDay1Route
  '/portofino/day-2': typeof PortofinoDay2Route
  '/portofino/day-3': typeof PortofinoDay3Route
  '/portofino/day-4': typeof PortofinoDay4Route
  '/portofino/day-5': typeof PortofinoDay5Route
  '/admin/': typeof AdminIndexRoute
  '/admin/hero-outfit/$id': typeof AdminHeroOutfitIdRoute
  '/portofino/$day/$look': typeof PortofinoDayLookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRouteWithChildren
  '/destinations': typeof DestinationsRouteWithChildren
  '/my-edit': typeof MyEditRoute
  '/portofino': typeof PortofinoRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resort-edits': typeof ResortEditsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/buying-office': typeof AdminBuyingOfficeRoute
  '/admin/day-images': typeof AdminDayImagesRoute
  '/admin/destination-moments': typeof AdminDestinationMomentsRoute
  '/admin/editorial-memory': typeof AdminEditorialMemoryRoute
  '/admin/founder-looks': typeof AdminFounderLooksRoute
  '/admin/inventory-health': typeof AdminInventoryHealthRoute
  '/admin/product-vault': typeof AdminProductVaultRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/look/$slug': typeof LookSlugRoute
  '/portofino/$moment': typeof PortofinoMomentRoute
  '/portofino/day-1': typeof PortofinoDay1Route
  '/portofino/day-2': typeof PortofinoDay2Route
  '/portofino/day-3': typeof PortofinoDay3Route
  '/portofino/day-4': typeof PortofinoDay4Route
  '/portofino/day-5': typeof PortofinoDay5Route
  '/admin': typeof AdminIndexRoute
  '/admin/hero-outfit/$id': typeof AdminHeroOutfitIdRoute
  '/portofino/$day/$look': typeof PortofinoDayLookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRouteWithChildren
  '/destinations': typeof DestinationsRouteWithChildren
  '/my-edit': typeof MyEditRoute
  '/portofino': typeof PortofinoRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resort-edits': typeof ResortEditsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/buying-office': typeof AdminBuyingOfficeRoute
  '/admin/day-images': typeof AdminDayImagesRoute
  '/admin/destination-moments': typeof AdminDestinationMomentsRoute
  '/admin/editorial-memory': typeof AdminEditorialMemoryRoute
  '/admin/founder-looks': typeof AdminFounderLooksRoute
  '/admin/inventory-health': typeof AdminInventoryHealthRoute
  '/admin/product-vault': typeof AdminProductVaultRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/look/$slug': typeof LookSlugRoute
  '/portofino/$moment': typeof PortofinoMomentRoute
  '/portofino/day-1': typeof PortofinoDay1Route
  '/portofino/day-2': typeof PortofinoDay2Route
  '/portofino/day-3': typeof PortofinoDay3Route
  '/portofino/day-4': typeof PortofinoDay4Route
  '/portofino/day-5': typeof PortofinoDay5Route
  '/admin/': typeof AdminIndexRoute
  '/admin/hero-outfit/$id': typeof AdminHeroOutfitIdRoute
  '/portofino/$day/$look': typeof PortofinoDayLookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brands'
    | '/destinations'
    | '/my-edit'
    | '/portofino'
    | '/privacy-policy'
    | '/resort-edits'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/brands'
    | '/admin/buying-office'
    | '/admin/day-images'
    | '/admin/destination-moments'
    | '/admin/editorial-memory'
    | '/admin/founder-looks'
    | '/admin/inventory-health'
    | '/admin/product-vault'
    | '/admin/subscribers'
    | '/brands/$slug'
    | '/destinations/$slug'
    | '/look/$slug'
    | '/portofino/$moment'
    | '/portofino/day-1'
    | '/portofino/day-2'
    | '/portofino/day-3'
    | '/portofino/day-4'
    | '/portofino/day-5'
    | '/admin/'
    | '/admin/hero-outfit/$id'
    | '/portofino/$day/$look'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brands'
    | '/destinations'
    | '/my-edit'
    | '/portofino'
    | '/privacy-policy'
    | '/resort-edits'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/brands'
    | '/admin/buying-office'
    | '/admin/day-images'
    | '/admin/destination-moments'
    | '/admin/editorial-memory'
    | '/admin/founder-looks'
    | '/admin/inventory-health'
    | '/admin/product-vault'
    | '/admin/subscribers'
    | '/brands/$slug'
    | '/destinations/$slug'
    | '/look/$slug'
    | '/portofino/$moment'
    | '/portofino/day-1'
    | '/portofino/day-2'
    | '/portofino/day-3'
    | '/portofino/day-4'
    | '/portofino/day-5'
    | '/admin'
    | '/admin/hero-outfit/$id'
    | '/portofino/$day/$look'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brands'
    | '/destinations'
    | '/my-edit'
    | '/portofino'
    | '/privacy-policy'
    | '/resort-edits'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/brands'
    | '/admin/buying-office'
    | '/admin/day-images'
    | '/admin/destination-moments'
    | '/admin/editorial-memory'
    | '/admin/founder-looks'
    | '/admin/inventory-health'
    | '/admin/product-vault'
    | '/admin/subscribers'
    | '/brands/$slug'
    | '/destinations/$slug'
    | '/look/$slug'
    | '/portofino/$moment'
    | '/portofino/day-1'
    | '/portofino/day-2'
    | '/portofino/day-3'
    | '/portofino/day-4'
    | '/portofino/day-5'
    | '/admin/'
    | '/admin/hero-outfit/$id'
    | '/portofino/$day/$look'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrandsRoute: typeof BrandsRouteWithChildren
  DestinationsRoute: typeof DestinationsRouteWithChildren
  MyEditRoute: typeof MyEditRoute
  PortofinoRoute: typeof PortofinoRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResortEditsRoute: typeof ResortEditsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminBrandsRoute: typeof AdminBrandsRoute
  AdminBuyingOfficeRoute: typeof AdminBuyingOfficeRoute
  AdminDayImagesRoute: typeof AdminDayImagesRoute
  AdminDestinationMomentsRoute: typeof AdminDestinationMomentsRoute
  AdminEditorialMemoryRoute: typeof AdminEditorialMemoryRoute
  AdminFounderLooksRoute: typeof AdminFounderLooksRoute
  AdminInventoryHealthRoute: typeof AdminInventoryHealthRoute
  AdminProductVaultRoute: typeof AdminProductVaultRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  LookSlugRoute: typeof LookSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminHeroOutfitIdRoute: typeof AdminHeroOutfitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resort-edits': {
      id: '/resort-edits'
      path: '/resort-edits'
      fullPath: '/resort-edits'
      preLoaderRoute: typeof ResortEditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portofino': {
      id: '/portofino'
      path: '/portofino'
      fullPath: '/portofino'
      preLoaderRoute: typeof PortofinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-edit': {
      id: '/my-edit'
      path: '/my-edit'
      fullPath: '/my-edit'
      preLoaderRoute: typeof MyEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portofino/day-5': {
      id: '/portofino/day-5'
      path: '/day-5'
      fullPath: '/portofino/day-5'
      preLoaderRoute: typeof PortofinoDay5RouteImport
      parentRoute: typeof PortofinoRoute
    }
    '/portofino/day-4': {
      id: '/portofino/day-4'
      path: '/day-4'
      fullPath: '/portofino/day-4'
      preLoaderRoute: typeof PortofinoDay4RouteImport
      parentRoute: typeof PortofinoRoute
    }
    '/portofino/day-3': {
      id: '/portofino/day-3'
      path: '/day-3'
      fullPath: '/portofino/day-3'
      preLoaderRoute: typeof PortofinoDay3RouteImport
      parentRoute: typeof PortofinoRoute
    }
    '/portofino/day-2': {
      id: '/portofino/day-2'
      path: '/day-2'
      fullPath: '/portofino/day-2'
      preLoaderRoute: typeof PortofinoDay2RouteImport
      parentRoute: typeof PortofinoRoute
    }
    '/portofino/day-1': {
      id: '/portofino/day-1'
      path: '/day-1'
      fullPath: '/portofino/day-1'
      preLoaderRoute: typeof PortofinoDay1RouteImport
      parentRoute: typeof PortofinoRoute
    }
    '/portofino/$moment': {
      id: '/portofino/$moment'
      path: '/$moment'
      fullPath: '/portofino/$moment'
      preLoaderRoute: typeof PortofinoMomentRouteImport
      parentRoute: typeof PortofinoRoute
    }
    '/look/$slug': {
      id: '/look/$slug'
      path: '/look/$slug'
      fullPath: '/look/$slug'
      preLoaderRoute: typeof LookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/brands/$slug': {
      id: '/brands/$slug'
      path: '/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof BrandsSlugRouteImport
      parentRoute: typeof BrandsRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/admin/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/product-vault': {
      id: '/admin/product-vault'
      path: '/admin/product-vault'
      fullPath: '/admin/product-vault'
      preLoaderRoute: typeof AdminProductVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory-health': {
      id: '/admin/inventory-health'
      path: '/admin/inventory-health'
      fullPath: '/admin/inventory-health'
      preLoaderRoute: typeof AdminInventoryHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/founder-looks': {
      id: '/admin/founder-looks'
      path: '/admin/founder-looks'
      fullPath: '/admin/founder-looks'
      preLoaderRoute: typeof AdminFounderLooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/editorial-memory': {
      id: '/admin/editorial-memory'
      path: '/admin/editorial-memory'
      fullPath: '/admin/editorial-memory'
      preLoaderRoute: typeof AdminEditorialMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/destination-moments': {
      id: '/admin/destination-moments'
      path: '/admin/destination-moments'
      fullPath: '/admin/destination-moments'
      preLoaderRoute: typeof AdminDestinationMomentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/day-images': {
      id: '/admin/day-images'
      path: '/admin/day-images'
      fullPath: '/admin/day-images'
      preLoaderRoute: typeof AdminDayImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/buying-office': {
      id: '/admin/buying-office'
      path: '/admin/buying-office'
      fullPath: '/admin/buying-office'
      preLoaderRoute: typeof AdminBuyingOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/brands': {
      id: '/admin/brands'
      path: '/admin/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portofino/$day/$look': {
      id: '/portofino/$day/$look'
      path: '/$day/$look'
      fullPath: '/portofino/$day/$look'
      preLoaderRoute: typeof PortofinoDayLookRouteImport
      parentRoute: typeof PortofinoRoute
    }
    '/admin/hero-outfit/$id': {
      id: '/admin/hero-outfit/$id'
      path: '/admin/hero-outfit/$id'
      fullPath: '/admin/hero-outfit/$id'
      preLoaderRoute: typeof AdminHeroOutfitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BrandsRouteChildren {
  BrandsSlugRoute: typeof BrandsSlugRoute
}

const BrandsRouteChildren: BrandsRouteChildren = {
  BrandsSlugRoute: BrandsSlugRoute,
}

const BrandsRouteWithChildren =
  BrandsRoute._addFileChildren(BrandsRouteChildren)

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

interface PortofinoRouteChildren {
  PortofinoMomentRoute: typeof PortofinoMomentRoute
  PortofinoDay1Route: typeof PortofinoDay1Route
  PortofinoDay2Route: typeof PortofinoDay2Route
  PortofinoDay3Route: typeof PortofinoDay3Route
  PortofinoDay4Route: typeof PortofinoDay4Route
  PortofinoDay5Route: typeof PortofinoDay5Route
  PortofinoDayLookRoute: typeof PortofinoDayLookRoute
}

const PortofinoRouteChildren: PortofinoRouteChildren = {
  PortofinoMomentRoute: PortofinoMomentRoute,
  PortofinoDay1Route: PortofinoDay1Route,
  PortofinoDay2Route: PortofinoDay2Route,
  PortofinoDay3Route: PortofinoDay3Route,
  PortofinoDay4Route: PortofinoDay4Route,
  PortofinoDay5Route: PortofinoDay5Route,
  PortofinoDayLookRoute: PortofinoDayLookRoute,
}

const PortofinoRouteWithChildren = PortofinoRoute._addFileChildren(
  PortofinoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrandsRoute: BrandsRouteWithChildren,
  DestinationsRoute: DestinationsRouteWithChildren,
  MyEditRoute: MyEditRoute,
  PortofinoRoute: PortofinoRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResortEditsRoute: ResortEditsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminBrandsRoute: AdminBrandsRoute,
  AdminBuyingOfficeRoute: AdminBuyingOfficeRoute,
  AdminDayImagesRoute: AdminDayImagesRoute,
  AdminDestinationMomentsRoute: AdminDestinationMomentsRoute,
  AdminEditorialMemoryRoute: AdminEditorialMemoryRoute,
  AdminFounderLooksRoute: AdminFounderLooksRoute,
  AdminInventoryHealthRoute: AdminInventoryHealthRoute,
  AdminProductVaultRoute: AdminProductVaultRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  LookSlugRoute: LookSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminHeroOutfitIdRoute: AdminHeroOutfitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
