/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResortEditsRouteImport } from './routes/resort-edits'
import { Route as PortofinoEditRouteImport } from './routes/portofino-edit'
import { Route as PortofinoRouteImport } from './routes/portofino'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortofinoDayChar123dayChar125RouteImport } from './routes/portofino.day-{$day}'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as BrandsSlugRouteImport } from './routes/brands.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResortEditsRoute = ResortEditsRouteImport.update({
  id: '/resort-edits',
  path: '/resort-edits',
  getParentRoute: () => rootRouteImport,
} as any)
const PortofinoEditRoute = PortofinoEditRouteImport.update({
  id: '/portofino-edit',
  path: '/portofino-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PortofinoRoute = PortofinoRouteImport.update({
  id: '/portofino',
  path: '/portofino',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortofinoDayChar123dayChar125Route =
  PortofinoDayChar123dayChar125RouteImport.update({
    id: '/day-{$day}',
    path: '/day-{$day}',
    getParentRoute: () => PortofinoRoute,
  } as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)
const BrandsSlugRoute = BrandsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BrandsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRouteWithChildren
  '/destinations': typeof DestinationsRouteWithChildren
  '/portofino': typeof PortofinoRouteWithChildren
  '/portofino-edit': typeof PortofinoEditRoute
  '/resort-edits': typeof ResortEditsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/portofino/day-{$day}': typeof PortofinoDayChar123dayChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRouteWithChildren
  '/destinations': typeof DestinationsRouteWithChildren
  '/portofino': typeof PortofinoRouteWithChildren
  '/portofino-edit': typeof PortofinoEditRoute
  '/resort-edits': typeof ResortEditsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/portofino/day-{$day}': typeof PortofinoDayChar123dayChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRouteWithChildren
  '/destinations': typeof DestinationsRouteWithChildren
  '/portofino': typeof PortofinoRouteWithChildren
  '/portofino-edit': typeof PortofinoEditRoute
  '/resort-edits': typeof ResortEditsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/portofino/day-{$day}': typeof PortofinoDayChar123dayChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brands'
    | '/destinations'
    | '/portofino'
    | '/portofino-edit'
    | '/resort-edits'
    | '/sitemap.xml'
    | '/brands/$slug'
    | '/destinations/$slug'
    | '/portofino/day-{$day}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brands'
    | '/destinations'
    | '/portofino'
    | '/portofino-edit'
    | '/resort-edits'
    | '/sitemap.xml'
    | '/brands/$slug'
    | '/destinations/$slug'
    | '/portofino/day-{$day}'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brands'
    | '/destinations'
    | '/portofino'
    | '/portofino-edit'
    | '/resort-edits'
    | '/sitemap.xml'
    | '/brands/$slug'
    | '/destinations/$slug'
    | '/portofino/day-{$day}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrandsRoute: typeof BrandsRouteWithChildren
  DestinationsRoute: typeof DestinationsRouteWithChildren
  PortofinoRoute: typeof PortofinoRouteWithChildren
  PortofinoEditRoute: typeof PortofinoEditRoute
  ResortEditsRoute: typeof ResortEditsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resort-edits': {
      id: '/resort-edits'
      path: '/resort-edits'
      fullPath: '/resort-edits'
      preLoaderRoute: typeof ResortEditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portofino-edit': {
      id: '/portofino-edit'
      path: '/portofino-edit'
      fullPath: '/portofino-edit'
      preLoaderRoute: typeof PortofinoEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portofino': {
      id: '/portofino'
      path: '/portofino'
      fullPath: '/portofino'
      preLoaderRoute: typeof PortofinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portofino/day-{$day}': {
      id: '/portofino/day-{$day}'
      path: '/day-{$day}'
      fullPath: '/portofino/day-{$day}'
      preLoaderRoute: typeof PortofinoDayChar123dayChar125RouteImport
      parentRoute: typeof PortofinoRoute
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/brands/$slug': {
      id: '/brands/$slug'
      path: '/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof BrandsSlugRouteImport
      parentRoute: typeof BrandsRoute
    }
  }
}

interface BrandsRouteChildren {
  BrandsSlugRoute: typeof BrandsSlugRoute
}

const BrandsRouteChildren: BrandsRouteChildren = {
  BrandsSlugRoute: BrandsSlugRoute,
}

const BrandsRouteWithChildren =
  BrandsRoute._addFileChildren(BrandsRouteChildren)

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

interface PortofinoRouteChildren {
  PortofinoDayChar123dayChar125Route: typeof PortofinoDayChar123dayChar125Route
}

const PortofinoRouteChildren: PortofinoRouteChildren = {
  PortofinoDayChar123dayChar125Route: PortofinoDayChar123dayChar125Route,
}

const PortofinoRouteWithChildren = PortofinoRoute._addFileChildren(
  PortofinoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrandsRoute: BrandsRouteWithChildren,
  DestinationsRoute: DestinationsRouteWithChildren,
  PortofinoRoute: PortofinoRouteWithChildren,
  PortofinoEditRoute: PortofinoEditRoute,
  ResortEditsRoute: ResortEditsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
