/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as MyEditRouteImport } from './routes/my-edit'
import { Route as PortofinoRouteImport } from './routes/portofino'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBrandsRouteImport } from './routes/admin.brands'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminEditorialIntelligenceRouteImport } from './routes/admin.editorial-intelligence'
import { Route as AdminLooksRouteImport } from './routes/admin.looks'
import { Route as AdminProductAuditRouteImport } from './routes/admin.product-audit'
import { Route as AdminProductHealthRouteImport } from './routes/admin.product-health'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as BrandsSlugRouteImport } from './routes/brands.$slug'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as PortofinoIndexRouteImport } from './routes/portofino.index'
import { Route as PortofinoMomentRouteImport } from './routes/portofino.$moment'
import { Route as AdminHeroOutfitIdRouteImport } from './routes/admin.hero-outfit.$id'
import { Route as AdminProductHealthQueueRouteImport } from './routes/admin.product-health_.queue'
import { Route as ApiPublicMcpRouteImport } from './routes/api/public/mcp'
import { Route as ApiPublicProductAuditRouteImport } from './routes/api/public/product-audit'
import { Route as ApiPublicProductHealthSweepRouteImport } from './routes/api/public/product-health-sweep'
import { Route as PortofinoDayLookRouteImport } from './routes/portofino.$day.$look'
import { Route as AdminMomentsIdRunRouteImport } from './routes/admin.moments.$id.run'
import { Route as ApiPublicChar91DotmcpChar93ListToolsRouteImport } from './routes/api/public/[.mcp]/list-tools'
import { Route as ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/api/public/[.well-known]/oauth-protected-resource'
import { Route as ApiPublicChar91DotmcpChar93InvokeToolToolRouteImport } from './routes/api/public/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEditRoute = MyEditRouteImport.update({
  id: '/my-edit',
  path: '/my-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PortofinoRoute = PortofinoRouteImport.update({
  id: '/portofino',
  path: '/portofino',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandsRoute = AdminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditorialIntelligenceRoute =
  AdminEditorialIntelligenceRouteImport.update({
    id: '/editorial-intelligence',
    path: '/editorial-intelligence',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminLooksRoute = AdminLooksRouteImport.update({
  id: '/looks',
  path: '/looks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductAuditRoute = AdminProductAuditRouteImport.update({
  id: '/product-audit',
  path: '/product-audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductHealthRoute = AdminProductHealthRouteImport.update({
  id: '/product-health',
  path: '/product-health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandsRoute,
} as any)
const BrandsSlugRoute = BrandsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BrandsRoute,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DestinationsRoute,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)
const PortofinoIndexRoute = PortofinoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortofinoRoute,
} as any)
const PortofinoMomentRoute = PortofinoMomentRouteImport.update({
  id: '/$moment',
  path: '/$moment',
  getParentRoute: () => PortofinoRoute,
} as any)
const AdminHeroOutfitIdRoute = AdminHeroOutfitIdRouteImport.update({
  id: '/hero-outfit/$id',
  path: '/hero-outfit/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductHealthQueueRoute = AdminProductHealthQueueRouteImport.update({
  id: '/product-health_/queue',
  path: '/product-health/queue',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductAuditRoute = ApiPublicProductAuditRouteImport.update({
  id: '/api/public/product-audit',
  path: '/api/public/product-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductHealthSweepRoute =
  ApiPublicProductHealthSweepRouteImport.update({
    id: '/api/public/product-health-sweep',
    path: '/api/public/product-health-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortofinoDayLookRoute = PortofinoDayLookRouteImport.update({
  id: '/$day/$look',
  path: '/$day/$look',
  getParentRoute: () => PortofinoRoute,
} as any)
const AdminMomentsIdRunRoute = AdminMomentsIdRunRouteImport.update({
  id: '/moments/$id/run',
  path: '/moments/$id/run',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicChar91DotmcpChar93ListToolsRoute =
  ApiPublicChar91DotmcpChar93ListToolsRouteImport.update({
    id: '/api/public/.mcp/list-tools',
    path: '/api/public/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRoute =
  ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/api/public/.well-known/oauth-protected-resource',
    path: '/api/public/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicChar91DotmcpChar93InvokeToolToolRoute =
  ApiPublicChar91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/api/public/.mcp/invoke-tool/$tool',
    path: '/api/public/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/brands': typeof BrandsRouteWithChildren
  '/destinations': typeof DestinationsRouteWithChildren
  '/my-edit': typeof MyEditRoute
  '/portofino': typeof PortofinoRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/editorial-intelligence': typeof AdminEditorialIntelligenceRoute
  '/admin/looks': typeof AdminLooksRoute
  '/admin/product-audit': typeof AdminProductAuditRoute
  '/admin/product-health': typeof AdminProductHealthRoute
  '/admin/system': typeof AdminSystemRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/portofino/$moment': typeof PortofinoMomentRoute
  '/admin/': typeof AdminIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/portofino/': typeof PortofinoIndexRoute
  '/admin/hero-outfit/$id': typeof AdminHeroOutfitIdRoute
  '/admin/product-health/queue': typeof AdminProductHealthQueueRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/product-audit': typeof ApiPublicProductAuditRoute
  '/api/public/product-health-sweep': typeof ApiPublicProductHealthSweepRoute
  '/portofino/$day/$look': typeof PortofinoDayLookRoute
  '/admin/moments/$id/run': typeof AdminMomentsIdRunRoute
  '/api/public/.mcp/list-tools': typeof ApiPublicChar91DotmcpChar93ListToolsRoute
  '/api/public/.well-known/oauth-protected-resource': typeof ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/public/.mcp/invoke-tool/$tool': typeof ApiPublicChar91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/my-edit': typeof MyEditRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/editorial-intelligence': typeof AdminEditorialIntelligenceRoute
  '/admin/looks': typeof AdminLooksRoute
  '/admin/product-audit': typeof AdminProductAuditRoute
  '/admin/product-health': typeof AdminProductHealthRoute
  '/admin/system': typeof AdminSystemRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/portofino/$moment': typeof PortofinoMomentRoute
  '/admin': typeof AdminIndexRoute
  '/brands': typeof BrandsIndexRoute
  '/destinations': typeof DestinationsIndexRoute
  '/portofino': typeof PortofinoIndexRoute
  '/admin/hero-outfit/$id': typeof AdminHeroOutfitIdRoute
  '/admin/product-health/queue': typeof AdminProductHealthQueueRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/product-audit': typeof ApiPublicProductAuditRoute
  '/api/public/product-health-sweep': typeof ApiPublicProductHealthSweepRoute
  '/portofino/$day/$look': typeof PortofinoDayLookRoute
  '/admin/moments/$id/run': typeof AdminMomentsIdRunRoute
  '/api/public/.mcp/list-tools': typeof ApiPublicChar91DotmcpChar93ListToolsRoute
  '/api/public/.well-known/oauth-protected-resource': typeof ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/public/.mcp/invoke-tool/$tool': typeof ApiPublicChar91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/brands': typeof BrandsRouteWithChildren
  '/destinations': typeof DestinationsRouteWithChildren
  '/my-edit': typeof MyEditRoute
  '/portofino': typeof PortofinoRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/editorial-intelligence': typeof AdminEditorialIntelligenceRoute
  '/admin/looks': typeof AdminLooksRoute
  '/admin/product-audit': typeof AdminProductAuditRoute
  '/admin/product-health': typeof AdminProductHealthRoute
  '/admin/system': typeof AdminSystemRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/portofino/$moment': typeof PortofinoMomentRoute
  '/admin/': typeof AdminIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/portofino/': typeof PortofinoIndexRoute
  '/admin/hero-outfit/$id': typeof AdminHeroOutfitIdRoute
  '/admin/product-health_/queue': typeof AdminProductHealthQueueRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/product-audit': typeof ApiPublicProductAuditRoute
  '/api/public/product-health-sweep': typeof ApiPublicProductHealthSweepRoute
  '/portofino/$day/$look': typeof PortofinoDayLookRoute
  '/admin/moments/$id/run': typeof AdminMomentsIdRunRoute
  '/api/public/.mcp/list-tools': typeof ApiPublicChar91DotmcpChar93ListToolsRoute
  '/api/public/.well-known/oauth-protected-resource': typeof ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/public/.mcp/invoke-tool/$tool': typeof ApiPublicChar91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/brands'
    | '/destinations'
    | '/my-edit'
    | '/portofino'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/brands'
    | '/admin/catalog'
    | '/admin/editorial-intelligence'
    | '/admin/looks'
    | '/admin/product-audit'
    | '/admin/product-health'
    | '/admin/system'
    | '/brands/$slug'
    | '/destinations/$slug'
    | '/portofino/$moment'
    | '/admin/'
    | '/brands/'
    | '/destinations/'
    | '/portofino/'
    | '/admin/hero-outfit/$id'
    | '/admin/product-health/queue'
    | '/api/public/mcp'
    | '/api/public/product-audit'
    | '/api/public/product-health-sweep'
    | '/portofino/$day/$look'
    | '/admin/moments/$id/run'
    | '/api/public/.mcp/list-tools'
    | '/api/public/.well-known/oauth-protected-resource'
    | '/api/public/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/my-edit'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/brands'
    | '/admin/catalog'
    | '/admin/editorial-intelligence'
    | '/admin/looks'
    | '/admin/product-audit'
    | '/admin/product-health'
    | '/admin/system'
    | '/brands/$slug'
    | '/destinations/$slug'
    | '/portofino/$moment'
    | '/admin'
    | '/brands'
    | '/destinations'
    | '/portofino'
    | '/admin/hero-outfit/$id'
    | '/admin/product-health/queue'
    | '/api/public/mcp'
    | '/api/public/product-audit'
    | '/api/public/product-health-sweep'
    | '/portofino/$day/$look'
    | '/admin/moments/$id/run'
    | '/api/public/.mcp/list-tools'
    | '/api/public/.well-known/oauth-protected-resource'
    | '/api/public/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/brands'
    | '/destinations'
    | '/my-edit'
    | '/portofino'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/brands'
    | '/admin/catalog'
    | '/admin/editorial-intelligence'
    | '/admin/looks'
    | '/admin/product-audit'
    | '/admin/product-health'
    | '/admin/system'
    | '/brands/$slug'
    | '/destinations/$slug'
    | '/portofino/$moment'
    | '/admin/'
    | '/brands/'
    | '/destinations/'
    | '/portofino/'
    | '/admin/hero-outfit/$id'
    | '/admin/product-health_/queue'
    | '/api/public/mcp'
    | '/api/public/product-audit'
    | '/api/public/product-health-sweep'
    | '/portofino/$day/$look'
    | '/admin/moments/$id/run'
    | '/api/public/.mcp/list-tools'
    | '/api/public/.well-known/oauth-protected-resource'
    | '/api/public/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BrandsRoute: typeof BrandsRouteWithChildren
  DestinationsRoute: typeof DestinationsRouteWithChildren
  MyEditRoute: typeof MyEditRoute
  PortofinoRoute: typeof PortofinoRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
  ApiPublicProductAuditRoute: typeof ApiPublicProductAuditRoute
  ApiPublicProductHealthSweepRoute: typeof ApiPublicProductHealthSweepRoute
  ApiPublicChar91DotmcpChar93ListToolsRoute: typeof ApiPublicChar91DotmcpChar93ListToolsRoute
  ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRoute: typeof ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRoute
  ApiPublicChar91DotmcpChar93InvokeToolToolRoute: typeof ApiPublicChar91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-edit': {
      id: '/my-edit'
      path: '/my-edit'
      fullPath: '/my-edit'
      preLoaderRoute: typeof MyEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portofino': {
      id: '/portofino'
      path: '/portofino'
      fullPath: '/portofino'
      preLoaderRoute: typeof PortofinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brands': {
      id: '/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/editorial-intelligence': {
      id: '/admin/editorial-intelligence'
      path: '/editorial-intelligence'
      fullPath: '/admin/editorial-intelligence'
      preLoaderRoute: typeof AdminEditorialIntelligenceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/looks': {
      id: '/admin/looks'
      path: '/looks'
      fullPath: '/admin/looks'
      preLoaderRoute: typeof AdminLooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/product-audit': {
      id: '/admin/product-audit'
      path: '/product-audit'
      fullPath: '/admin/product-audit'
      preLoaderRoute: typeof AdminProductAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/product-health': {
      id: '/admin/product-health'
      path: '/product-health'
      fullPath: '/admin/product-health'
      preLoaderRoute: typeof AdminProductHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/brands/': {
      id: '/brands/'
      path: '/'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof BrandsRoute
    }
    '/brands/$slug': {
      id: '/brands/$slug'
      path: '/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof BrandsSlugRouteImport
      parentRoute: typeof BrandsRoute
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/portofino/': {
      id: '/portofino/'
      path: '/'
      fullPath: '/portofino/'
      preLoaderRoute: typeof PortofinoIndexRouteImport
      parentRoute: typeof PortofinoRoute
    }
    '/portofino/$moment': {
      id: '/portofino/$moment'
      path: '/$moment'
      fullPath: '/portofino/$moment'
      preLoaderRoute: typeof PortofinoMomentRouteImport
      parentRoute: typeof PortofinoRoute
    }
    '/admin/hero-outfit/$id': {
      id: '/admin/hero-outfit/$id'
      path: '/hero-outfit/$id'
      fullPath: '/admin/hero-outfit/$id'
      preLoaderRoute: typeof AdminHeroOutfitIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/product-health_/queue': {
      id: '/admin/product-health_/queue'
      path: '/product-health/queue'
      fullPath: '/admin/product-health/queue'
      preLoaderRoute: typeof AdminProductHealthQueueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/product-audit': {
      id: '/api/public/product-audit'
      path: '/api/public/product-audit'
      fullPath: '/api/public/product-audit'
      preLoaderRoute: typeof ApiPublicProductAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/product-health-sweep': {
      id: '/api/public/product-health-sweep'
      path: '/api/public/product-health-sweep'
      fullPath: '/api/public/product-health-sweep'
      preLoaderRoute: typeof ApiPublicProductHealthSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portofino/$day/$look': {
      id: '/portofino/$day/$look'
      path: '/$day/$look'
      fullPath: '/portofino/$day/$look'
      preLoaderRoute: typeof PortofinoDayLookRouteImport
      parentRoute: typeof PortofinoRoute
    }
    '/admin/moments/$id/run': {
      id: '/admin/moments/$id/run'
      path: '/moments/$id/run'
      fullPath: '/admin/moments/$id/run'
      preLoaderRoute: typeof AdminMomentsIdRunRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/.mcp/list-tools': {
      id: '/api/public/.mcp/list-tools'
      path: '/api/public/.mcp/list-tools'
      fullPath: '/api/public/.mcp/list-tools'
      preLoaderRoute: typeof ApiPublicChar91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/.well-known/oauth-protected-resource': {
      id: '/api/public/.well-known/oauth-protected-resource'
      path: '/api/public/.well-known/oauth-protected-resource'
      fullPath: '/api/public/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/.mcp/invoke-tool/$tool': {
      id: '/api/public/.mcp/invoke-tool/$tool'
      path: '/api/public/.mcp/invoke-tool/$tool'
      fullPath: '/api/public/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof ApiPublicChar91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBrandsRoute: typeof AdminBrandsRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminEditorialIntelligenceRoute: typeof AdminEditorialIntelligenceRoute
  AdminLooksRoute: typeof AdminLooksRoute
  AdminProductAuditRoute: typeof AdminProductAuditRoute
  AdminProductHealthRoute: typeof AdminProductHealthRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminHeroOutfitIdRoute: typeof AdminHeroOutfitIdRoute
  AdminProductHealthQueueRoute: typeof AdminProductHealthQueueRoute
  AdminMomentsIdRunRoute: typeof AdminMomentsIdRunRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBrandsRoute: AdminBrandsRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminEditorialIntelligenceRoute: AdminEditorialIntelligenceRoute,
  AdminLooksRoute: AdminLooksRoute,
  AdminProductAuditRoute: AdminProductAuditRoute,
  AdminProductHealthRoute: AdminProductHealthRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminHeroOutfitIdRoute: AdminHeroOutfitIdRoute,
  AdminProductHealthQueueRoute: AdminProductHealthQueueRoute,
  AdminMomentsIdRunRoute: AdminMomentsIdRunRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BrandsRouteChildren {
  BrandsSlugRoute: typeof BrandsSlugRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
}

const BrandsRouteChildren: BrandsRouteChildren = {
  BrandsSlugRoute: BrandsSlugRoute,
  BrandsIndexRoute: BrandsIndexRoute,
}

const BrandsRouteWithChildren =
  BrandsRoute._addFileChildren(BrandsRouteChildren)

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

interface PortofinoRouteChildren {
  PortofinoMomentRoute: typeof PortofinoMomentRoute
  PortofinoIndexRoute: typeof PortofinoIndexRoute
  PortofinoDayLookRoute: typeof PortofinoDayLookRoute
}

const PortofinoRouteChildren: PortofinoRouteChildren = {
  PortofinoMomentRoute: PortofinoMomentRoute,
  PortofinoIndexRoute: PortofinoIndexRoute,
  PortofinoDayLookRoute: PortofinoDayLookRoute,
}

const PortofinoRouteWithChildren = PortofinoRoute._addFileChildren(
  PortofinoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BrandsRoute: BrandsRouteWithChildren,
  DestinationsRoute: DestinationsRouteWithChildren,
  MyEditRoute: MyEditRoute,
  PortofinoRoute: PortofinoRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
  ApiPublicProductAuditRoute: ApiPublicProductAuditRoute,
  ApiPublicProductHealthSweepRoute: ApiPublicProductHealthSweepRoute,
  ApiPublicChar91DotmcpChar93ListToolsRoute:
    ApiPublicChar91DotmcpChar93ListToolsRoute,
  ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRoute:
    ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiPublicChar91DotmcpChar93InvokeToolToolRoute:
    ApiPublicChar91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
